//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastbootEnhance.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FastbootEnhance.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fastboot Enhance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開発者: LibXZR @ akr-developers.com に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無効 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string disabled {
            get {
                return ResourceManager.GetString("disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enabled {
            get {
                return ResourceManager.GetString("enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_0_size {
            get {
                return ResourceManager.GetString("fastboot_0_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロパティ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_basic_prop {
            get {
                return ResourceManager.GetString("fastboot_basic_prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダブルクリックで対象のデバイスを選択: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_choose_device {
            get {
                return ResourceManager.GetString("fastboot_choose_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仮想A/B一時パーティションが存在します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_cow_exist_str0 {
            get {
                return ResourceManager.GetString("fastboot_cow_exist_str0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仮想A/Bパーティションのアップデート時に作成された一時パーティションがデバイス内に存在する為、無理に続行をするとsuperパーティションの容量不足によりデバイスが文鎮化する可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_cow_exist_str1 {
            get {
                return ResourceManager.GetString("fastboot_cow_exist_str1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (仮想A/Bのアップデート中でなければ「COW」で終わる一時パーティションを手動で削除すればこの警告を解消することが可能です) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_cow_exist_str2 {
            get {
                return ResourceManager.GetString("fastboot_cow_exist_str2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   続行をしますか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_cow_exist_str3 {
            get {
                return ResourceManager.GetString("fastboot_cow_exist_str3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しい論理パーティションの作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_create_dynamic_partition {
            get {
                return ResourceManager.GetString("fastboot_create_dynamic_partition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のデバイス:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_current_device {
            get {
                return ResourceManager.GetString("fastboot_current_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のスロット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_current_slot {
            get {
                return ResourceManager.GetString("fastboot_current_slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバイス名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_device {
            get {
                return ResourceManager.GetString("fastboot_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバイス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_device_name {
            get {
                return ResourceManager.GetString("fastboot_device_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象デバイスがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_device_not_exist {
            get {
                return ResourceManager.GetString("fastboot_device_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fastboot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_enhance {
            get {
                return ResourceManager.GetString("fastboot_enhance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   論理パーティションの拡張 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_expand_dynamic_partition {
            get {
                return ResourceManager.GetString("fastboot_expand_dynamic_partition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前で絞り込む: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_filter_by_partition_name {
            get {
                return ResourceManager.GetString("fastboot_filter_by_partition_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Payload.binを書き込む に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_flash_payload {
            get {
                return ResourceManager.GetString("fastboot_flash_payload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明なパーティションを無視 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_ignore_unknown {
            get {
                return ResourceManager.GetString("fastboot_ignore_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fastbootdで実行中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_is_userspace {
            get {
                return ResourceManager.GetString("fastboot_is_userspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この操作では複数のパーティションを選択することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_not_support_multiselect {
            get {
                return ResourceManager.GetString("fastboot_not_support_multiselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この操作は論理パーティションでのみ可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_only_logical {
            get {
                return ResourceManager.GetString("fastboot_only_logical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アクション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_partition_action {
            get {
                return ResourceManager.GetString("fastboot_partition_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_partition_action_create {
            get {
                return ResourceManager.GetString("fastboot_partition_action_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_partition_action_delete {
            get {
                return ResourceManager.GetString("fastboot_partition_action_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   消去 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_partition_action_erase {
            get {
                return ResourceManager.GetString("fastboot_partition_action_erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書き込み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_partition_action_flash {
            get {
                return ResourceManager.GetString("fastboot_partition_action_flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リサイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_partition_action_resize {
            get {
                return ResourceManager.GetString("fastboot_partition_action_resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   論理パーティション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_partition_is_dynamic {
            get {
                return ResourceManager.GetString("fastboot_partition_is_dynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_partition_name {
            get {
                return ResourceManager.GetString("fastboot_partition_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パーティション名が空欄です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_partition_name_empty {
            get {
                return ResourceManager.GetString("fastboot_partition_name_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_partition_size {
            get {
                return ResourceManager.GetString("fastboot_partition_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ (B) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_partition_size_b {
            get {
                return ResourceManager.GetString("fastboot_partition_size_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パーティションサイズが空欄です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_partition_size_empty {
            get {
                return ResourceManager.GetString("fastboot_partition_size_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パーティションサイズが無効です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_partition_size_invalid {
            get {
                return ResourceManager.GetString("fastboot_partition_size_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パーティションの縮小ができません。パーティションの削除をしてから再作成であれば可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_partition_size_unable_shrink {
            get {
                return ResourceManager.GetString("fastboot_partition_size_unable_shrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パーティション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_partition_table {
            get {
                return ResourceManager.GetString("fastboot_partition_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_prop_name {
            get {
                return ResourceManager.GetString("fastboot_prop_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_prop_value {
            get {
                return ResourceManager.GetString("fastboot_prop_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bootloaderで再起動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_reboot_bootloader {
            get {
                return ResourceManager.GetString("fastboot_reboot_bootloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fastbootdで再起動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_reboot_fastbootd {
            get {
                return ResourceManager.GetString("fastboot_reboot_fastbootd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recoveryで再起動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_reboot_recovery {
            get {
                return ResourceManager.GetString("fastboot_reboot_recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Systemで再起動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_reboot_system {
            get {
                return ResourceManager.GetString("fastboot_reboot_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切断 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_remove_device {
            get {
                return ResourceManager.GetString("fastboot_remove_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シームレスアップデートに対応 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_seamless_update {
            get {
                return ResourceManager.GetString("fastboot_seamless_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セキュアブート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_secure_boot {
            get {
                return ResourceManager.GetString("fastboot_secure_boot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シリアルナンバー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_serial_num {
            get {
                return ResourceManager.GetString("fastboot_serial_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スロットAに変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_setactive_a {
            get {
                return ResourceManager.GetString("fastboot_setactive_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スロットBに変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_setactive_b {
            get {
                return ResourceManager.GetString("fastboot_setactive_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログを表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_show_logs {
            get {
                return ResourceManager.GetString("fastboot_show_logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象のパーティションが未選択です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_target_partition_not_selected {
            get {
                return ResourceManager.GetString("fastboot_target_partition_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   以下の書き込むパーティションが不明な場合があります: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_unknown_partition_str0 {
            get {
                return ResourceManager.GetString("fastboot_unknown_partition_str0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明なパーティションを無視にチェックを入れるとこの警告を無効にすることができます。未知のパーティションですがデバイスの書き込みに失敗したり、文鎮化する訳ではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_unknown_partition_str1 {
            get {
                return ResourceManager.GetString("fastboot_unknown_partition_str1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fastbootdモードの再起動が必要な可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_unknown_partition_str2 {
            get {
                return ResourceManager.GetString("fastboot_unknown_partition_str2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システムアップデートの状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_update_status {
            get {
                return ResourceManager.GetString("fastboot_update_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マージ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_update_status_merging {
            get {
                return ResourceManager.GetString("fastboot_update_status_merging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_update_status_none {
            get {
                return ResourceManager.GetString("fastboot_update_status_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スナップショット済み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_update_status_snapshotted {
            get {
                return ResourceManager.GetString("fastboot_update_status_snapshotted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システムアップデート中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_vab_staging_str0 {
            get {
                return ResourceManager.GetString("fastboot_vab_staging_str0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバイスのシステムアップデート中です。操作を強制するとデバイスが文鎮化する可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_vab_staging_str1 {
            get {
                return ResourceManager.GetString("fastboot_vab_staging_str1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (デバイスのシステムアップデートが完了するまでしばらくお待ちください) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_vab_staging_str2 {
            get {
                return ResourceManager.GetString("fastboot_vab_staging_str2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   続行をしますか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_vab_staging_str3 {
            get {
                return ResourceManager.GetString("fastboot_vab_staging_str3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   vbmetaのVerificationを無効化しますか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_vbmeta_disable_verify {
            get {
                return ResourceManager.GetString("fastboot_vbmeta_disable_verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verificationを無効化 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string fastboot_vbmeta_disable_verify_title {
            get {
                return ResourceManager.GetString("fastboot_vbmeta_disable_verify_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログを記録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string logger {
            get {
                return ResourceManager.GetString("logger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いいえ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GitHub に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string open_source {
            get {
                return ResourceManager.GetString("open_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   操作が完了しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string operation_completed {
            get {
                return ResourceManager.GetString("operation_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   操作はサポートされていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string operation_not_supported {
            get {
                return ResourceManager.GetString("operation_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロパティ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_basic_properties {
            get {
                return ResourceManager.GetString("payload_basic_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブロックサイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_blocksize {
            get {
                return ResourceManager.GetString("payload_blocksize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   参照 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_browse {
            get {
                return ResourceManager.GetString("payload_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   現在のファイル:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_current_file {
            get {
                return ResourceManager.GetString("payload_current_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Blobのサイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_data_size {
            get {
                return ResourceManager.GetString("payload_data_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Payload Dumper に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_dumper {
            get {
                return ResourceManager.GetString("payload_dumper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動的パーティションのメタデータ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_dynamic_partition_metadata {
            get {
                return ResourceManager.GetString("payload_dynamic_partition_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_error_occur {
            get {
                return ResourceManager.GetString("payload_error_occur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明な操作を無視 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_extract_ignore_unknown {
            get {
                return ResourceManager.GetString("payload_extract_ignore_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェックサムを無視 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_extract_ignore_verify {
            get {
                return ResourceManager.GetString("payload_extract_ignore_verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   イメージを抽出する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_extract_image {
            get {
                return ResourceManager.GetString("payload_extract_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インクリメンタルを許可 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_extract_incremental {
            get {
                return ResourceManager.GetString("payload_extract_incremental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   抽出のオプション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_extract_options {
            get {
                return ResourceManager.GetString("payload_extract_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フルパッケージ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_full_package {
            get {
                return ResourceManager.GetString("payload_full_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インクリメンタルパッケージからイメージを抽出できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_incremental_warning {
            get {
                return ResourceManager.GetString("payload_incremental_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マニフェストのサイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_manifest_size {
            get {
                return ResourceManager.GetString("payload_manifest_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メタデータの署名 (Base64) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_metadata_signature {
            get {
                return ResourceManager.GetString("payload_metadata_signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メタデータの署名のサイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_metadata_signature_size {
            get {
                return ResourceManager.GetString("payload_metadata_signature_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動的パーティションのメタデータがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_no_dynamic_metadata {
            get {
                return ResourceManager.GetString("payload_no_dynamic_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Payloadを指定していない場合は、「参照」をクリックまたは「ファイルをドラッグ&amp;ドロップ」してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_no_file_str {
            get {
                return ResourceManager.GetString("payload_no_file_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Payloadに含まれるパーティション:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_partition_group_include {
            get {
                return ResourceManager.GetString("payload_partition_group_include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パーティションのグループ名:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_partition_group_name {
            get {
                return ResourceManager.GetString("payload_partition_group_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パーティションのグループサイズ:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_partition_group_size {
            get {
                return ResourceManager.GetString("payload_partition_group_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パーティション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_partitions {
            get {
                return ResourceManager.GetString("payload_partitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前で絞り込む: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_partitions_filter_by_name {
            get {
                return ResourceManager.GetString("payload_partitions_filter_by_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェックサム (Base64) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_partitions_hash {
            get {
                return ResourceManager.GetString("payload_partitions_hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_partitions_name {
            get {
                return ResourceManager.GetString("payload_partitions_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_partitions_size {
            get {
                return ResourceManager.GetString("payload_partitions_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_property_name {
            get {
                return ResourceManager.GetString("payload_property_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_property_value {
            get {
                return ResourceManager.GetString("payload_property_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_remove_file {
            get {
                return ResourceManager.GetString("payload_remove_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   署名 (Base64) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_signature {
            get {
                return ResourceManager.GetString("payload_signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   署名のサイズ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_signature_size {
            get {
                return ResourceManager.GetString("payload_signature_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スナップショットが有効:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_snapshot_enabled {
            get {
                return ResourceManager.GetString("payload_snapshot_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   抽出する対象パーティションが未選択です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_target_partition_not_selected {
            get {
                return ResourceManager.GetString("payload_target_partition_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイムスタンプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_timestamp {
            get {
                return ResourceManager.GetString("payload_timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   複数ファイルのドロップはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_unable_drop_multifile {
            get {
                return ResourceManager.GetString("payload_unable_drop_multifile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル形式の互換性がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_unsupported_format {
            get {
                return ResourceManager.GetString("payload_unsupported_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Payloadのバージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string payload_version {
            get {
                return ResourceManager.GetString("payload_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログラムは既に実行中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string program_already_running {
            get {
                return ResourceManager.GetString("program_already_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リリース先: www.akr-developers.com に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string release_at {
            get {
                return ResourceManager.GetString("release_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存するパスを選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string select_save_path {
            get {
                return ResourceManager.GetString("select_save_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スレッド に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string visit_thread {
            get {
                return ResourceManager.GetString("visit_thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はい に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
